// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentFinishGood.Repositories;

#nullable disable

namespace ShipmentFinishGood.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811070624_AddExcelUploadSession")]
    partial class AddExcelUploadSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShipmentFinishGood.Models.BarcodeUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsScanned")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScannedBy")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ShipmentGroupId");

                    b.ToTable("BarcodeUnits");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ExcelUploadItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("ModelProduk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoPO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProcessedPOId")
                        .HasColumnType("int");

                    b.Property<int>("QtyTotal")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("SessionId");

                    b.ToTable("ExcelUploadItems");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ExcelUploadSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.ToTable("ExcelUploadSessions");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.GroupBreakdown", b =>
                {
                    b.Property<int>("ShipmentGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IntegrityOk")
                        .HasColumnType("bit");

                    b.Property<int>("PcsPerBox")
                        .HasColumnType("int");

                    b.Property<int>("PcsPerPallet")
                        .HasColumnType("int");

                    b.Property<int>("QtyBox")
                        .HasColumnType("int");

                    b.Property<int>("QtyPallet")
                        .HasColumnType("int");

                    b.Property<int>("QtyPcs")
                        .HasColumnType("int");

                    b.Property<int>("QtyTotal")
                        .HasColumnType("int");

                    b.HasKey("ShipmentGroupId");

                    b.ToTable("GroupBreakdowns");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PcsPerBox")
                        .HasColumnType("int");

                    b.Property<int>("PcsPerPallet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelCode", "Method", "IsActive");

                    b.ToTable("ModelConfigs");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.PO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NoPO")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("POs");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ShipmentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayNoPO")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("GroupSignature")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("MixedPO")
                        .HasColumnType("bit");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipmentMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GroupSignature")
                        .IsUnique();

                    b.ToTable("ShipmentGroups");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ShipmentGroupPO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("POId")
                        .HasColumnType("int");

                    b.Property<int>("QtyContribution")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POId");

                    b.HasIndex("ShipmentGroupId");

                    b.ToTable("ShipmentGroupPOs");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.BarcodeUnit", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.ShipmentGroup", "ShipmentGroup")
                        .WithMany()
                        .HasForeignKey("ShipmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentGroup");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ExcelUploadItem", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.ExcelUploadSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.GroupBreakdown", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.ShipmentGroup", "ShipmentGroup")
                        .WithOne("Breakdown")
                        .HasForeignKey("ShipmentFinishGood.Models.GroupBreakdown", "ShipmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentGroup");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ShipmentGroupPO", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.PO", "PO")
                        .WithMany()
                        .HasForeignKey("POId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipmentFinishGood.Models.ShipmentGroup", "ShipmentGroup")
                        .WithMany("POs")
                        .HasForeignKey("ShipmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PO");

                    b.Navigation("ShipmentGroup");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ExcelUploadSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ShipmentGroup", b =>
                {
                    b.Navigation("Breakdown");

                    b.Navigation("POs");
                });
#pragma warning restore 612, 618
        }
    }
}
