// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentFinishGood.Repositories;

#nullable disable

namespace ShipmentFinishGood.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250812045548_AddPOTablesAndBarcode")]
    partial class AddPOTablesAndBarcode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShipmentFinishGood.Models.BarcodeRegistry", b =>
                {
                    b.Property<int>("BarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarcodeId"));

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarcodeId");

                    b.HasIndex("BarcodeValue")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("BarcodeRegistries");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ModelConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PcsPerBox")
                        .HasColumnType("int");

                    b.Property<int>("PcsPerPallet")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId");

                    b.ToTable("ModelConfigurations");

                    b.HasData(
                        new
                        {
                            ConfigId = 1,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-D10EB-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 192,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 2,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-D10EG-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 192,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 3,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-D10EG-W",
                            PcsPerBox = 3,
                            PcsPerPallet = 192,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 4,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-D10GN-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 192,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 5,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "R-2255-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 6,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2450-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 7,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DEB-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 8,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DEE-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 9,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DEG-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 10,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DGN-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 11,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DGT-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 12,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DPC-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 13,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DP-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 14,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DP-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 15,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-2400DLJ-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 240,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 16,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P155-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 17,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P55-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 18,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P150DEG-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 19,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P150DGC-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 20,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P150DGT-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 21,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P150DBAGA",
                            PcsPerBox = 20,
                            PcsPerPallet = 800,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 22,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DGC-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 23,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DGC-R",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 24,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DEG-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 25,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DLJ-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 26,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DPR-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 27,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-P50DPP-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 28,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-562DDGC-K",
                            PcsPerBox = 5,
                            PcsPerPallet = 350,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 29,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-U156-S",
                            PcsPerBox = 6,
                            PcsPerPallet = 450,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 30,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-NA35R-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 31,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-NA35R",
                            PcsPerBox = 20,
                            PcsPerPallet = 1000,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 32,
                            Description = "LOOSE (Pengiriman tanpa palet)",
                            ModelName = "RF-5270LJ-K",
                            PcsPerBox = 20,
                            PcsPerPallet = 600,
                            Type = "LOOSE"
                        },
                        new
                        {
                            ConfigId = 33,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-562DDGC-K",
                            PcsPerBox = 5,
                            PcsPerPallet = 210,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 34,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-P150DGC-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1600,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 35,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-P150DEG-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1600,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 36,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-P50DGC-R",
                            PcsPerBox = 20,
                            PcsPerPallet = 1600,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 37,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-P50DEG-S",
                            PcsPerBox = 20,
                            PcsPerPallet = 1200,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 38,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-D10EG-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 144,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 39,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-D10GN-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 126,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 40,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2450-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 41,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "R-2255-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 42,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DPC-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 43,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DP-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 44,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DP-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 45,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DEE-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 46,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DEG-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 47,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DGN-S",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        },
                        new
                        {
                            ConfigId = 48,
                            Description = "PALLET (Pengiriman dengan palet)",
                            ModelName = "RF-2400DEB-K",
                            PcsPerBox = 3,
                            PcsPerPallet = 216,
                            Type = "PALLET"
                        });
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.PODetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ScannedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScannedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailId");

                    b.HasIndex("POId");

                    b.ToTable("PODetails");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.POMaster", b =>
                {
                    b.Property<int>("POId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POId"));

                    b.Property<string>("Container")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoInvoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyBox")
                        .HasColumnType("int");

                    b.Property<int>("QtyPallet")
                        .HasColumnType("int");

                    b.Property<int>("QtyPcs")
                        .HasColumnType("int");

                    b.Property<int>("QtyTotal")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("POId");

                    b.HasIndex("SourceSessionId");

                    b.ToTable("POMasters");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.ScanningActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("ScanningActivities");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.UploadSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityQRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SheetIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBoxes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("UploadSessions");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.UploadSessionDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalPO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalQty")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("SessionId");

                    b.ToTable("UploadSessionDetails");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.BarcodeRegistry", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.UploadSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.PODetail", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.POMaster", "PO")
                        .WithMany("Details")
                        .HasForeignKey("POId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PO");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.POMaster", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.UploadSession", "SourceSession")
                        .WithMany("POMasters")
                        .HasForeignKey("SourceSessionId");

                    b.Navigation("SourceSession");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.UploadSessionDetail", b =>
                {
                    b.HasOne("ShipmentFinishGood.Models.UploadSession", "Session")
                        .WithMany("Details")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.POMaster", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ShipmentFinishGood.Models.UploadSession", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("POMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
